[build]
    command = "npm run netlify-install && cd packages/cli-dev-build && npx gulp buildNetlify"
    publish = "packages/netlify"
    ignore = "git diff --quiet HEAD^ HEAD packages/dashboard packages/storybook-shared packages/theme packages/netlify packages/shared"
[build.environment]
    NPM_FLAGS="--prefix=/dev/null"
